import { expect, test } from '@playwright/test'
import { installMockApi, openApplication, signIn } from './support/mockApi'

test('登录注册页使用 Element Plus 滚动条，不让浏览器页面滚动', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 500 })
  await page.goto('/register')
  const wrap = page.locator('.auth-scroll > .el-scrollbar__wrap')
  await expect.poll(() => wrap.evaluate((element) => element.scrollHeight > element.clientHeight)).toBe(true)
  await wrap.hover()
  await page.mouse.wheel(0, 500)
  await expect.poll(() => wrap.evaluate((element) => element.scrollTop)).toBeGreaterThan(0)
  expect(await page.evaluate(() => window.scrollY)).toBe(0)
})

test('文档正文、目录和 Markdown 横向区域使用 Element Plus 滚动条', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 600 })
  await installMockApi(page)
  await signIn(page)
  await page.getByRole('button', { name: '打开导航' }).click()
  await page.getByRole('link', { name: '开发文档' }).click()
  await page.locator('.docs-card').filter({ hasText: '计算 Hash' }).click()

  const mainWrap = page.locator('.docs-main-scroll > .el-scrollbar__wrap')
  await expect.poll(() => mainWrap.evaluate((element) => element.scrollHeight > element.clientHeight)).toBe(true)
  await mainWrap.hover()
  await page.mouse.wheel(0, 600)
  await expect.poll(() => mainWrap.evaluate((element) => element.scrollTop)).toBeGreaterThan(0)
  expect(await page.evaluate(() => window.scrollY)).toBe(0)
  await expect(page.locator('.docs-sidebar-scroll > .el-scrollbar__wrap')).toHaveCount(1)
  await expect(page.locator('.docs-table-scroll > .el-scrollbar__wrap').first()).toHaveCount(1)
  await expect(page.locator('.docs-code-scroll > .el-scrollbar__wrap').first()).toHaveCount(1)
  const tableWrap = page.locator('.docs-table-scroll > .el-scrollbar__wrap').first()
  await expect.poll(() => tableWrap.evaluate((element) => element.scrollWidth > element.clientWidth)).toBe(true)
  await tableWrap.evaluate((element) => { element.scrollLeft = 80 })
  expect(await tableWrap.evaluate((element) => element.scrollLeft)).toBeGreaterThan(0)
})

test('桌面文档目录锚点仍在正文滚动区定位', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 600 })
  await installMockApi(page)
  await signIn(page)
  await page.getByRole('link', { name: '开发文档' }).click()
  await page.locator('.docs-card').filter({ hasText: '计算 Hash' }).click()
  const mainWrap = page.locator('.docs-main-scroll > .el-scrollbar__wrap')
  await expect.poll(() => mainWrap.evaluate((element) => element.scrollHeight > element.clientHeight)).toBe(true)
  const toc = page.getByRole('complementary', { name: '本页目录' })
  await expect(toc.locator('.el-scrollbar__wrap')).toHaveCount(1)
  await toc.getByRole('link', { name: '错误说明' }).click()
  await expect.poll(() => page.evaluate(() => decodeURIComponent(location.hash))).toBe('#错误说明')
  await expect.poll(() => mainWrap.evaluate((element) => element.scrollTop)).toBeGreaterThan(0)
  await expect(toc.getByRole('link', { name: '错误说明' })).toHaveClass(/is-active/)
  expect(await page.evaluate(() => window.scrollY)).toBe(0)
})

test('Usage 调用记录的横向滚动由 Element Plus 接管', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await installMockApi(page)
  await openApplication(page)
  await page.getByRole('navigation', { name: '应用详情分区' }).getByRole('link', { name: 'API Keys' }).click()
  await page.getByRole('link', { name: '查看详情' }).click()
  await page.getByRole('navigation', { name: 'API Key 详情分区' }).getByRole('link', { name: '调用统计' }).click()
  const wrap = page.locator('.events-scroll > .el-scrollbar__wrap')
  await expect.poll(() => wrap.evaluate((element) => element.scrollWidth > element.clientWidth)).toBe(true)
  await wrap.evaluate((element) => { element.scrollLeft = 90 })
  expect(await wrap.evaluate((element) => element.scrollLeft)).toBeGreaterThan(0)
  await expect(page.locator('.chart-scroll > .el-scrollbar__wrap')).toHaveCount(1)
})
